language: node_js
node_js:
  - 6.2.2
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g gulp-cli
services: mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
